Feature profile page skeleton
hatchways/team-pretzel pull request #58
Opened 2019-11-13 18:27 UTC by m3tron

Refactored dashboard with AppBar and Drawer which included friendsList.

2019-11-13 21:15 UTC, skassam21 reviewed
Small comments

2019-11-13 21:15 UTC, skassam21 commented on client/src/App.jsx
> +import Dashboard from "./pages/Dashboard/index";
let's be consistent with naming conventions - I more commonly see with React the name of the files are the name of the components and are PascalCase

2019-11-13 21:15 UTC, skassam21 commented on client/src/components/AppBarDrawer/index.js
> +  // },
remove commented out code

2019-11-13 21:15 UTC, skassam21 commented on client/src/components/AppBarDrawer/index.js
> +      <CssBaseline />
I beleive CssBaseline shouold only exist at the top level react component

2019-11-13 21:15 UTC, skassam21 commented on client/src/components/FriendList/index.js
> +  //title: { flexGrow: 1 }
again commented out code

2019-11-13 21:15 UTC, skassam21 commented on client/src/components/FriendList/index.js
> +      <Typography variant="h4" className={classes.title}>
need some padding or margin here for the friends title

2019-11-14 22:18 UTC, chungleee approved these changes

2019-11-14 23:32 UTC, k-awe-some requested changes
Profile page looks solid yet Create new poll is not letting user upload images, code looks fine to me so I'm thinking conflicts come from `PollDialog` being used in 2 places (`AppBarDrawer` and `NavBar`) ?!

also if we could all use `.jsx` for React components that'd be more consistent.

2019-11-14 23:32 UTC, k-awe-some commented on client/src/App.jsx
> +import Dashboard from "./pages/Dashboard.js";
can we possibly combine the two Dashboard components into one `Dashboard.jsx` file?

2019-11-15 19:19 UTC, merged